version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: thunder_user
      POSTGRES_PASSWORD: thunder
      POSTGRES_DB: tropic_thunder_db
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/database

volumes:
  postgres-data:

networks:
  postgres-network: